### ISSUE TITLE
memory Error

### ISSUE THREAD

**Issue by newmluser** [roatienza/Deep-Learning-Experiments#22]
Hi,
When I increase the size of the file I see  I am getting memory Error.

Looks 

> 
 content = np.array(content)

is not able to get more data into the buffer (100MB Text file).
is there a way (or) any suggestions to make this same program work for large amount of data

**Comment by roatienza** [comment]
If you need to load huge data from filesystem, I recommend Data Generator. Pls see this tutorial:

https://stanford.edu/~shervine/blog/keras-how-to-generate-data-on-the-fly
