### ISSUE TITLE
generate time series with gan

### ISSUE THREAD

**Issue by jnees88** [roatienza/Deep-Learning-Experiments#25]
Hello
I want to generate fake time series using Gan's networks, but I can't use your network. I wanted you to help me if possible. Thankful

**Comment by roatienza** [comment]
Better if an auto-regressive model is used not GAN.

**Comment by jnees88** [comment]
​[Look up details](https://translate.google.com/details)
156 / 5,000
Translation results
Translation result
Hello
Thank you for your guidance
But my data has 10,240 features and I could not get the results from your suggested method to generate fake data.
Thank you for your help
