### ISSUE TITLE
Adviсe about keras GAN

### ISSUE THREAD

**Issue by hadaev8** [roatienza/Deep-Learning-Experiments#8]
I'm trying on the basis of your example make a generator of color images.
But missing something with the color dimension.
And get error:
number of input channels does not match corresponding dimension of filter, 1 != 3

Code
https://pastebin.com/TAm21NJg

**Comment by roatienza** [comment]
You may have to modify the number of channels output of the generator from 1 to 3.

self.G.add(Conv2DTranspose(1, 5, padding='same'))
